version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "go dependencies"
      - "deps"
    assignees:
      - "obalunenko"
    reviewers:
      - "obalunenko"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "deps"
    assignees:
      - "obalunenko"
    reviewers:
      - "obalunenko"
    commit-message:
      prefix: "chore"
      include: "scope"
